metrics:
  global:
    scrape_interval: 30s
    scrape_timeout: 30s
    remote_write:
      - url: https://prometheus-us-central1.grafana.net/api/prom/push
        basic_auth:
          username: ${GRAFANA_USER}
          password: ${GRAFANA_PASS}
  configs:
    - name: hydra
      host_filter: false
      scrape_configs:
        - job_name: hydrabooster
          honor_timestamps: true
          honor_labels: true
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets: ['localhost:8888']
          relabel_configs:
            - source_labels: [__address__]
              replacement: ${HYDRA_NAME}
              target_label: name
